env:
  global:
language: node_js
node_js:
  - node
notifications:
  - false
script:
  - yarn format:check
  - yarn lint:check
  - yarn build
  - npx html-validator-cli --verbose --file src/index.html
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: production
  local_dir: './dist'
  fqdn: 'bolabuari.com'
  target_branch: master
  project_name: 'Bola Buari Portfolio'
  committer_from_gh: true
  verbose: true
  name: 'Bola Buari'
  email: 'bola_ahmed2002@yahoo.com'
  commit_message: 'Deploy to github pages - master'
