name: All Jobs Scraper

on:
  schedule:
    - cron: '5 4 * * 2,4,6' # At 04:05 on Tuesday, Thursday, and Saturday..
  workflow_dispatch:

env:
  DETECTLANG_API_KEY_0: ${{ secrets.DETECTLANG_API_KEY_0 }}
  DETECTLANG_API_KEY_1: ${{ secrets.DETECTLANG_API_KEY_1 }}
  DETECTLANG_API_KEY_2: ${{ secrets.DETECTLANG_API_KEY_2 }}
  DETECTLANG_API_KEY_3: ${{ secrets.DETECTLANG_API_KEY_3 }}
  DETECTLANG_API_KEY_4: ${{ secrets.DETECTLANG_API_KEY_4 }}
  DETECTLANG_API_KEY_5: ${{ secrets.DETECTLANG_API_KEY_5 }}
  DETECTLANG_API_KEY_6: ${{ secrets.DETECTLANG_API_KEY_6 }}
  DETECTLANG_API_KEY_7: ${{ secrets.DETECTLANG_API_KEY_7 }}
  DETECTLANG_API_KEY_8: ${{ secrets.DETECTLANG_API_KEY_8 }}

jobs:
  scrape:
    runs-on: ubuntu-22.04
    name: Scrape Job Data

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          working-directory: 'job_scraper'
      - name: Run Script to scrape data
        run: cd job_scraper && bundle exec bin/main.rb
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'
      - name: Install required dependency for node
        run: yarn install
      - name: Run Prettier
        run: yarn format
      - name: Save generated data
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_options: '--no-verify'
          push_options: '--no-verify --force'
          commit_user_name: Bola Ahmed Buari
          commit_user_email: 36057474+bolah2009@users.noreply.github.com
          commit_author: Bola Ahmed Buari <36057474+bolah2009@users.noreply.github.com>
          commit_message: 'ci: save generated all jobs data [skip actions]'
