name: Auto Merge Dependabot PRs
on: pull_request

permissions:
  pull-requests: write
  issues: write
  repository-projects: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          GH_TOKEN: ${{secrets.DEPENDABOT_GITHUB_TOKEN}}
          PR_URL: ${{github.event.pull_request.html_url}}
